/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import huyphpk00628_asm_gd2.HUYPHPK00628_ASM_GD2;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pham tuan
 */
public class Trangchu extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    /**
     * Creates new form Trangchu
     */
    public Trangchu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHoadon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCtHoadon = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hdso = new javax.swing.JTextField();
        ngay = new javax.swing.JTextField();
        makhhoadon = new javax.swing.JTextField();
        trigia = new javax.swing.JTextField();
        themHoadon = new javax.swing.JButton();
        xoaHoadon = new javax.swing.JButton();
        suaHoadon = new javax.swing.JButton();
        resetHoadon = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        hdsoCtHoadon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mahhCtHoadon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        soluongCtHoadon = new javax.swing.JTextField();
        SuaCtHoadon = new javax.swing.JButton();
        resetCtHoadon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableHanghoa = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mahh = new javax.swing.JTextField();
        tenhh = new javax.swing.JTextField();
        quycach = new javax.swing.JTextField();
        donvitinh = new javax.swing.JTextField();
        dongia = new javax.swing.JTextField();
        themhh = new javax.swing.JButton();
        xoahh = new javax.swing.JButton();
        suahh = new javax.swing.JButton();
        resethh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableKhachHang = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        makh = new javax.swing.JTextField();
        tenkh = new javax.swing.JTextField();
        dthoai = new javax.swing.JTextField();
        themkh = new javax.swing.JButton();
        xoakh = new javax.swing.JButton();
        editkh = new javax.swing.JButton();
        resetkh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Trang chủ");
        jInternalFrame1.setVisible(true);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bảng hóa đơn");

        TableHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hóa đơn số", "Ngày", "Mã khách hàng", "Trị giá"
            }
        ));
        TableHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableHoadon);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bảng chi tiết hóa đơn");

        TableCtHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hóa đơn số", "Mã hàng hóa", "Số lượng"
            }
        ));
        TableCtHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCtHoadonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableCtHoadon);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Hóa đơn số:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày lập hóa đơn:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mã khách hàng:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Trị giá:");

        themHoadon.setText("Thêm ");
        themHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themHoadonActionPerformed(evt);
            }
        });

        xoaHoadon.setText("Xóa");
        xoaHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaHoadonActionPerformed(evt);
            }
        });

        suaHoadon.setText("Sửa");
        suaHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaHoadonActionPerformed(evt);
            }
        });

        resetHoadon.setText("Reset");
        resetHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetHoadonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hóa đơn số:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã hàng hóa:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Số lượng:");

        SuaCtHoadon.setText("Sửa");
        SuaCtHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaCtHoadonActionPerformed(evt);
            }
        });

        resetCtHoadon.setText("Reset");
        resetCtHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCtHoadonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mahhCtHoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(hdsoCtHoadon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(soluongCtHoadon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SuaCtHoadon)
                        .addGap(18, 18, 18)
                        .addComponent(resetCtHoadon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hdso)
                            .addComponent(ngay)
                            .addComponent(makhhoadon)
                            .addComponent(trigia, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(themHoadon)
                        .addGap(18, 18, 18)
                        .addComponent(xoaHoadon)
                        .addGap(18, 18, 18)
                        .addComponent(suaHoadon)
                        .addGap(18, 18, 18)
                        .addComponent(resetHoadon)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hdso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(makhhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(trigia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themHoadon)
                            .addComponent(xoaHoadon)
                            .addComponent(suaHoadon)
                            .addComponent(resetHoadon))
                        .addGap(49, 49, 49)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hdsoCtHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mahhCtHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(soluongCtHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SuaCtHoadon)
                            .addComponent(resetCtHoadon))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hóa đơn", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Bảng hàng hóa");

        TableHanghoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hàng hóa", "Tên hàng hóa", "Quy cách", "Đơn vị tính", "Đơn giá"
            }
        ));
        TableHanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHanghoaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableHanghoa);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mã hàng hóa:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tên hàng hóa:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Quy cách:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Đơn vị tính:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Đơn giá:");

        themhh.setText("Thêm");
        themhh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themhhActionPerformed(evt);
            }
        });

        xoahh.setText("Xóa");
        xoahh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoahhActionPerformed(evt);
            }
        });

        suahh.setText("Sửa");
        suahh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suahhActionPerformed(evt);
            }
        });

        resethh.setText("Reset");
        resethh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resethhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mahh)
                            .addComponent(tenhh)
                            .addComponent(quycach)
                            .addComponent(donvitinh)
                            .addComponent(dongia, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(themhh)
                                .addGap(18, 18, 18)
                                .addComponent(xoahh)
                                .addGap(26, 26, 26)
                                .addComponent(suahh)
                                .addGap(18, 18, 18)
                                .addComponent(resethh)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(mahh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tenhh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(quycach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(donvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themhh)
                            .addComponent(xoahh)
                            .addComponent(suahh)
                            .addComponent(resethh))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hàng hóa", jPanel2);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Bảng khách hàng");

        TableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Điện thoại"
            }
        ));
        TableKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKhachHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableKhachHang);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Mã khách hàng:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tên khách hàng:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Điện thoại:");

        themkh.setText("Thêm");
        themkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themkhActionPerformed(evt);
            }
        });

        xoakh.setText("Xóa");
        xoakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoakhActionPerformed(evt);
            }
        });

        editkh.setText("Sửa");
        editkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editkhActionPerformed(evt);
            }
        });

        resetkh.setText("Reset");
        resetkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetkhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(makh)
                                    .addComponent(tenkh)
                                    .addComponent(dthoai, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(themkh)
                                .addGap(18, 18, 18)
                                .addComponent(xoakh)
                                .addGap(18, 18, 18)
                                .addComponent(editkh)
                                .addGap(18, 18, 18)
                                .addComponent(resetkh))))
                    .addComponent(jLabel16))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(dthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themkh)
                            .addComponent(xoakh)
                            .addComponent(editkh)
                            .addComponent(resetkh))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Khách hàng", jPanel3);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Hóa đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetHoadonActionPerformed
        // TODO add your handling code here:
        this.hdso.setText("");
        this.ngay.setText("");
        this.makhhoadon.setText("");
        this.trigia.setText("");
    }//GEN-LAST:event_resetHoadonActionPerformed

    private void resetCtHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCtHoadonActionPerformed
        // TODO add your handling code here:
        this.hdsoCtHoadon.setText("");
        this.mahhCtHoadon.setText("");
        this.soluongCtHoadon.setText("");
    }//GEN-LAST:event_resetCtHoadonActionPerformed

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:
        GetDataTableKhachhang();
    }//GEN-LAST:event_jPanel3ComponentShown

    private void themkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themkhActionPerformed
        // TODO add your handling code here:
        String makh,tenkh,dthoai;
        makh = this.makh.getText();
        tenkh = this.tenkh.getText();
        dthoai = this.dthoai.getText();
        String query = "insert into Khachhang values("+ " N'" +makh+"' , '"+tenkh+"' ,N'"+dthoai+ "')";
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query); 
        GetDataTableKhachhang();
    }//GEN-LAST:event_themkhActionPerformed

    private void resetkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetkhActionPerformed
        // TODO add your handling code here:
       makh.setText("");
      tenkh.setText("");
       dthoai.setText("");
        
    }//GEN-LAST:event_resetkhActionPerformed

    private void TableKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKhachHangMouseClicked
        // TODO add your handling code here:
        int position = TableKhachHang.getSelectedRow();
        makh.setText(TableKhachHang.getValueAt(position, 0).toString());
        tenkh.setText(TableKhachHang.getValueAt(position, 1).toString());
        dthoai.setText(TableKhachHang.getValueAt(position, 2).toString());
    }//GEN-LAST:event_TableKhachHangMouseClicked

    private void xoakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoakhActionPerformed
        // TODO add your handling code here:
        String makh = this.makh.getText().toString();
        String query ="delete Khachhang where makh="+makh;
         huyphpk00628_asm_gd2.HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query);
         GetDataTableKhachhang();
    }//GEN-LAST:event_xoakhActionPerformed

    private void editkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editkhActionPerformed
        // TODO add your handling code here:
        String makh,tenkh,dthoai;
        makh = this.makh.getText();
        tenkh = this.tenkh.getText();
        dthoai = this.dthoai.getText();
        String query = "update Khachhang set "+ "makh= N'" +makh+"' ,tenkh= '"+tenkh+"' ,dthoai='"+dthoai+ "'where makh="+makh;
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query); 
        GetDataTableKhachhang();
        
    }//GEN-LAST:event_editkhActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        GetDataTableHanghoa();
    }//GEN-LAST:event_jPanel2ComponentShown

    private void TableHanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHanghoaMouseClicked
        // TODO add your handling code here:
        int position = TableHanghoa.getSelectedRow();
        mahh.setText(TableHanghoa.getValueAt(position, 0).toString());
        tenhh.setText(TableHanghoa.getValueAt(position, 1).toString());
        quycach.setText(TableHanghoa.getValueAt(position, 2).toString());
        donvitinh.setText(TableHanghoa.getValueAt(position, 3).toString());
        dongia.setText(TableHanghoa.getValueAt(position, 4).toString());
    }//GEN-LAST:event_TableHanghoaMouseClicked

    private void themhhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themhhActionPerformed
        // TODO add your handling code here:
        String mahh,tenhh,quycach,donvitinh,dongia;
        mahh = this.mahh.getText();
        tenhh = this.tenhh.getText();
        quycach = this.quycach.getText();
        donvitinh = this.donvitinh.getText();
        dongia = this.dongia.getText();
        String query = "insert into Hanghoa values("+ " N'"+mahh+"' , '"+tenhh+"' ,N'"+quycach+"' ,N'"+donvitinh+"' ,N'"+dongia+ "')";
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query); 
        GetDataTableHanghoa();
    }//GEN-LAST:event_themhhActionPerformed

    private void xoahhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoahhActionPerformed
        // TODO add your handling code here:
         String mahh = this.mahh.getText().toString();
        String query ="delete Hanghoa where mahh="+mahh;
         huyphpk00628_asm_gd2.HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query);
         GetDataTableHanghoa();
    }//GEN-LAST:event_xoahhActionPerformed

    private void resethhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resethhActionPerformed
        // TODO add your handling code here:
        mahh.setText("");
        tenhh.setText("");
        quycach.setText("");
        donvitinh.setText("");
        dongia.setText("");
    }//GEN-LAST:event_resethhActionPerformed

    private void suahhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suahhActionPerformed
        // TODO add your handling code here:
        String mahh,tenhh,quycach,donvitinh,dongia;
        mahh = this.mahh.getText();
        tenhh = this.tenhh.getText();
        quycach = this.quycach.getText();
        donvitinh = this.donvitinh.getText();
        dongia = this.dongia.getText();
        String query = "update Hanghoa set "+ "mahh= N'" +mahh+"' ,tenhh= '"+tenhh+"' ,quicach= '"+quycach+"' ,dvtinh= '"+donvitinh+"' ,dongia='"+dongia+ "'where mahh="+mahh;
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query); 
        GetDataTableHanghoa();
    }//GEN-LAST:event_suahhActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        GetDataTableHoadon();
        GetDataTableCtHoadon();
    }//GEN-LAST:event_jPanel1ComponentShown

    private void TableHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHoadonMouseClicked
        // TODO add your handling code here:
        int position = TableHoadon.getSelectedRow();
        hdso.setText(TableHoadon.getValueAt(position, 0).toString());
        ngay.setText(TableHoadon.getValueAt(position, 1).toString());
        makhhoadon.setText(TableHoadon.getValueAt(position, 2).toString());
        trigia.setText(TableHoadon.getValueAt(position, 3).toString());
    }//GEN-LAST:event_TableHoadonMouseClicked

    private void TableCtHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCtHoadonMouseClicked
        // TODO add your handling code here:
        int position = TableCtHoadon.getSelectedRow();
        hdsoCtHoadon.setText(TableCtHoadon.getValueAt(position, 0).toString());
        mahhCtHoadon.setText(TableCtHoadon.getValueAt(position, 1).toString());
        soluongCtHoadon.setText(TableCtHoadon.getValueAt(position, 2).toString());
    }//GEN-LAST:event_TableCtHoadonMouseClicked

    private void themHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themHoadonActionPerformed
        // TODO add your handling code here:
         String hdso,ngay,makhhoadon,trigia;
        hdso = this.hdso.getText();
        ngay = this.ngay.getText();
        makhhoadon = this.makhhoadon.getText();
        trigia = this.trigia.getText();
        String query = "insert into Hoadon values("+ " N'"+hdso+"' , '"+ngay+"' ,N'"+makhhoadon+"' ,N'"+trigia+ "')";     
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query);
        String query1 = "insert into Chitiethoadon values("+ " N'"+hdso+"' ,'',0)";     
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query1);
        GetDataTableHoadon();
        GetDataTableCtHoadon();
    }//GEN-LAST:event_themHoadonActionPerformed

    private void xoaHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaHoadonActionPerformed
        // TODO add your handling code here:
         String hdso = this.hdso.getText().toString();
        String query ="delete Hoadon where hdso="+hdso;
         huyphpk00628_asm_gd2.HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query);
         GetDataTableHoadon();
    }//GEN-LAST:event_xoaHoadonActionPerformed

    private void suaHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaHoadonActionPerformed
        // TODO add your handling code here:
         String hdso,ngay,makhhoadon,trigia;
        hdso = this.hdso.getText();
        ngay = this.ngay.getText();
        makhhoadon = this.makhhoadon.getText();
        trigia = this.trigia.getText();
        String query = "update Hoadon set "+ "hdso= N'" +hdso+"' ,ngay= '"+ngay+"' ,makh= '"+makhhoadon+"' ,trigia= '"+trigia+"'where hdso="+hdso;
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query); 
        GetDataTableHoadon();
    }//GEN-LAST:event_suaHoadonActionPerformed

    private void SuaCtHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaCtHoadonActionPerformed
        // TODO add your handling code here:
         String hdsoCtHoadon,mahhCtHoadon,soluongCtHoadon;
        hdsoCtHoadon = this.hdsoCtHoadon.getText();
        mahhCtHoadon = this.mahhCtHoadon.getText();
        soluongCtHoadon = this.soluongCtHoadon.getText();
        String query = "update Chititethoadon set "+ "hdso= N'" +hdsoCtHoadon+"' ,mahh= '"+mahhCtHoadon+"' ,soluong= '"+soluongCtHoadon+"'where hdso="+hdso;
        HUYPHPK00628_ASM_GD2.connection.ExcuteQueryUpdateDB(query); 
        GetDataTableCtHoadon();
    }//GEN-LAST:event_SuaCtHoadonActionPerformed

    public void GetDataTableKhachhang(){
        String query="";
        query ="select * from Khachhang";
        ResultSet rs = HUYPHPK00628_ASM_GD2.connection.ExcuteQueryGetTable(query);
        Object[] obj = new Object[]{"Mã khách hàng", "Tên khách hàng", "Điện thoại"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        TableKhachHang.setModel(tableModel);
        try {
            while(rs.next()){
                Object[] item = new Object[10];
                item[0] = rs.getString("makh");
                item[1] = rs.getString("tenkh");
                item[2] = rs.getString("dthoai");
                tableModel.addRow(item);
            }
        }catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    public  void GetDataTableHanghoa(){
        String query="";
        query ="select * from Hanghoa";
        ResultSet rs = HUYPHPK00628_ASM_GD2.connection.ExcuteQueryGetTable(query);
        Object[] obj = new Object[]{"Mã hàng hóa","Tên hàng hóa","Qui cách","Đơn vị tính","Đơn giá"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        TableHanghoa.setModel(tableModel);
        try{
            while(rs.next()){
                Object[] item = new Object[10];
                item[0] = rs.getString("mahh");
                item[1] = rs.getString("tenhh");
                item[2] = rs.getString("quicach");
                item[3] = rs.getString("dvtinh");
                item[4] = rs.getString("dongia");
                 tableModel.addRow(item);
            }
        }catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    public void GetDataTableHoadon(){
        String query="";
        query="select * from Hoadon";
        ResultSet rs = HUYPHPK00628_ASM_GD2.connection.ExcuteQueryGetTable(query);
        Object[] obj = new Object[]{"Hóa đơn số","Ngày","Mã khách hàng","Trị giá"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        TableHoadon.setModel(tableModel);
        try{
            while(rs.next()){
                Object[] item = new Object[10];
                item[0] =rs.getString("hdso");
                item[1] =rs.getString("ngay");
                item[2] =rs.getString("makh");
                item[3] =rs.getString("trigia");
                tableModel.addRow(item);
            }
        }catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    public void GetDataTableCtHoadon(){
        String query="";
        query="select * from Chitiethoadon";
        ResultSet rs = HUYPHPK00628_ASM_GD2.connection.ExcuteQueryGetTable(query);
        Object[] obj = new Object[]{"Hóa đơn số","Mã hàng hóa","Số lượng"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        TableCtHoadon.setModel(tableModel);
        try{
            while(rs.next()){
                Object[] item = new Object[10];
                item[0] =rs.getString("hdso");
                item[1] =rs.getString("mahh");
                item[2] =rs.getString("soluong");
                tableModel.addRow(item);
            }
        }catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trangchu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SuaCtHoadon;
    private javax.swing.JTable TableCtHoadon;
    private javax.swing.JTable TableHanghoa;
    private javax.swing.JTable TableHoadon;
    private javax.swing.JTable TableKhachHang;
    private javax.swing.JTextField dongia;
    private javax.swing.JTextField donvitinh;
    private javax.swing.JTextField dthoai;
    private javax.swing.JButton editkh;
    private javax.swing.JTextField hdso;
    private javax.swing.JTextField hdsoCtHoadon;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mahh;
    private javax.swing.JTextField mahhCtHoadon;
    private javax.swing.JTextField makh;
    private javax.swing.JTextField makhhoadon;
    private javax.swing.JTextField ngay;
    private javax.swing.JTextField quycach;
    private javax.swing.JButton resetCtHoadon;
    private javax.swing.JButton resetHoadon;
    private javax.swing.JButton resethh;
    private javax.swing.JButton resetkh;
    private javax.swing.JTextField soluongCtHoadon;
    private javax.swing.JButton suaHoadon;
    private javax.swing.JButton suahh;
    private javax.swing.JTextField tenhh;
    private javax.swing.JTextField tenkh;
    private javax.swing.JButton themHoadon;
    private javax.swing.JButton themhh;
    private javax.swing.JButton themkh;
    private javax.swing.JTextField trigia;
    private javax.swing.JButton xoaHoadon;
    private javax.swing.JButton xoahh;
    private javax.swing.JButton xoakh;
    // End of variables declaration//GEN-END:variables
}
